### ISSUE TITLE
Plan for supporting local runners

### ISSUE THREAD

**Issue by Xartos** [hashicorp/cluster-api-provider-terraform-cloud#12]
## What

I was wondering if there's any plans of supporting some type of local runner instead of relying on Terraform Cloud.

## Why

I could see situations where it's not possible to use Terraform Cloud for provisioning *(i.e. in a private-cloud type of situation)*.

## How

Either have the controller keep the state in cluster and run it directly instead of just triggering a run.
Alternatively have an external runner that the controller will trigger instead of Terraform Cloud to start a run.

I understand that this is just a technical preview as of now, but I was just curious if there's any plans for something like this in the future.

**Comment by arybolovlev** [comment]
Hi @Xartos,

Thank you for bringing up this question. We don't have any plans to support anything else but Terraform Cloud / Enterprise.

Thanks.
